Update docker-compose
Netflix/security_monkey pull request #1080
Opened 2018-05-29 05:52 UTC by r0hi7

Spinning up the compose in clean build environment, secmonkey-data
was throwing the error beacuse the postgres docker was not made to
create database with the name of secmonkey. This commit handles the
same.

2018-05-29 16:41 UTC, mikegrima requested changes

2018-05-29 16:41 UTC, mikegrima commented on docker-compose.yml
> -    #volumes:
Don't delete the commented out lines.

2018-05-30 04:00 UTC, r0hi7 commented on docker-compose.yml
> -    #volumes:
Updated this pull request.

2018-10-17 17:08 UTC, mikegrima commented
Wow sorry about that!

Merging in now.

2018-10-17 17:08 UTC, mikegrima approved these changes

2018-10-17 17:14 UTC, merged