Slackbot API Starter Implementation for Custom Alerting/Notifications on Slack
Netflix/security_monkey pull request #1089
Opened 2018-06-13 18:29 UTC by drewgallis

Adding a Custom Alerter - SlackBot API to send custom alerts, posting auditor/watcher changes on a slack channel. Fully integrates with automated scheduler, posting to slack channel when watchers/auditors are ran. Note: make sure you have it integrated as a custom alerter so it is called by watcher.py and auditor.py!

2018-06-13 18:30 UTC, drewgallis commented
@mikegrima Should be all fixed now to merge!

2018-06-13 18:53 UTC, drewgallis commented
@mikegrima a user needs to add their own api keys and that was making in a little hard to get around the build process, but I think I figured it out!

2018-06-13 20:12 UTC, drewgallis commented
@mikegrima builds passed!

2018-06-14 00:57 UTC, mikegrima commented
I need to review this.

2018-07-04 21:09 UTC, mikegrima requested changes
Please make the required fixes.

2018-07-04 21:09 UTC, mikegrima commented on security_monkey/alerters/custom_alerter.py
> +    print(os.environ) #remove if you don't need to check your env for your slack api token
Please remove this.

2018-07-04 21:09 UTC, mikegrima commented on security_monkey/alerters/custom_alerter.py
> +#UNCOMMENT ALL POSTMESSAGE FUNCTIONS WHEN YOUR SLACKCLIENT IS SETUP
I think the code should be set up such that an env variable or check is in place to only send messages when the slack client is fully operational.

Users should not have to make any modifications or changes to this code.

2018-07-04 21:09 UTC, mikegrima commented on security_monkey/alerters/custom_alerter.py
> +    print(watcher.deleted_items)
Remove `print` statements.

2018-07-04 21:09 UTC, mikegrima commented on security_monkey/alerters/custom_alerter.py
> +#UNCOMMENT ALL POSTMESSAGE FUNCTIONS WHEN YOUR SLACKCLIENT IS SETUP
See above comment.

2018-07-04 21:09 UTC, mikegrima commented on security_monkey/alerters/slack_post.py
> +    slack_token ="thisisatempkey" #use the one above when you are actually doing the setup
Remove this.

2018-07-04 21:09 UTC, mikegrima commented on security_monkey/alerters/slack_post.py
> +    sc = SlackClient(slack_token)
This should be moved to a package variable so that it doesn't need to be re-instantiated every time a `postMessage` is called.

2018-07-04 21:09 UTC, mikegrima commented on security_monkey/alerters/slack_post.py
> +    channel = 'CHANNEL ID HERE' #test by posting to your own slack channel id, can be changed to any channel
Env var and/or config var this.

2018-07-04 21:09 UTC, mikegrima commented on security_monkey/alerters/slack_post.py
> +    sc.api_call(
Env var and/or config var this.

2018-07-04 21:09 UTC, mikegrima commented on security_monkey/alerters/test_slack_message.py
> +#Just a quick program to test your communication of your slack bot and security monkey
For this, please consider mocking the slack client. I do something similar in HubCommander: 
https://github.com/Netflix/hubcommander/blob/develop/tests/conftest.py#L77-L83

I basically mock out the Slack Client, and then when it's used:
https://github.com/Netflix/hubcommander/blob/develop/tests/test_slack_comm.py#L14-L16 
^^ To verify what was passed in was correct.

2018-09-13 16:23 UTC, unacceptable commented
@drewgallis Can you make the changes requested by Mike?  I would like to try this out.

2019-03-11 16:51 UTC, closed without merging