Docs update
Netflix/security_monkey pull request #1208
Opened 2019-06-20 10:10 UTC by AdamKufel

Minor updates to docs

2019-06-20 16:42 UTC, mikegrima requested changes
The only change in the doc required is:
`    $ monkey add_account_aws --id $account --name $name --role_name SecurityMonkey`

The connection string does not contain a typo, `postgresql` is correct. The other changes are not needed.

2019-06-20 16:42 UTC, mikegrima commented on docs/docker.md
> +    you need to add an account for the scheduler to monitor. This can all be done one of two ways: 1. By modifying the `docker/api-init.sh` script to include the `monkey` commands. **PLEASE NOTE:** I
The numbers need to be on their own lines.

2019-06-21 07:49 UTC, AdamKufel commented
Indeed it contains a typo, in documentation (https://github.com/Netflix/security_monkey/blob/develop/docs/options.md) it's stated: 

> "SQLALCHEMY_DATABASE_URI = 'postgressql://\<user\>:\<password\>@\<hostname\>:5432/SecurityMonkey'"

there is "postgre**ss**ql" (double "ss") but correct protocol is "postgre**s**ql" (one "s")

2019-06-24 22:23 UTC, mikegrima commented
Sorry -- I misread.

Can you update your PR to only make those really small updates? Some of the numbering formatting is broken in the current PR.

2024-10-17 07:46 UTC, closed without merging