Fix storage of ACM certificates
Netflix/security_monkey pull request #1210
Opened 2019-06-21 10:56 UTC by pdallegrave

Problem
As referenced in #1209, the acm.py `slup()` method is not properly parsing ACM certificates that contain "UpdatedAt" key.

Fix
Add another conditional that will convert datetime object into ISO string.

2019-06-24 22:14 UTC, mikegrima commented
LGTM

2019-06-24 22:21 UTC, mikegrima requested changes

2019-06-24 22:21 UTC, mikegrima commented on security_monkey/watchers/acm.py
> +                        if config.get('RenewalSummary').get('UpdatedAt'):
Please update to:
```
if config.get('RenewalSummary', {}).get('UpdatedAt'):
    config['RenewalSummary']['UpdatedAt'] = config['RenewalSummary']['UpdatedAt'].astimezone(tzutc()).isoformat()
```

2019-06-26 08:13 UTC, pdallegrave commented on security_monkey/watchers/acm.py
> +                        if config.get('RenewalSummary').get('UpdatedAt'):
Changes applied.

2019-06-26 17:23 UTC, mikegrima approved these changes
LGTM

2019-06-26 17:23 UTC, merged